#!/bin/sh

head="#!/bin/sh\n";
command="\nyarn;\ngulp deploy;";


if [ ! -e .git/hooks/post-merge ];
then
    echo -e $head > .git/hooks/post-merge;
fi
echo -e $command >> .git/hooks/post-merge;


if [ ! -e .git/hooks/post-checkout ];
then
    echo -e $head > .git/hooks/post-checkout;
fi
echo -e $command >> .git/hooks/post-checkout;
